AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  htmx-shortener

Parameters:
  OAUTHKEY:
    Type: String
    NoEcho: true
  OAUTHSECRET:
    Type: String
    NoEcho: true

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ShortenerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: shortener/
      Handler: bootstrap 
      Runtime: provided.al2
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DDB_TABLE: !Ref ShortenerTable
          OAUTH_KEY: !Ref OAUTHKEY
          OAUTH_SECRET: !Ref OAUTHSECRET
          OAUTH_DOMAIN: "https://0cfxckhrtk.execute-api.us-east-2.amazonaws.com/Prod/login/google"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShortenerTable
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: makefile

  ShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: pk
          AttributeType: S
        -
          AttributeName: sk
          AttributeType: S
      KeySchema:
        -
          AttributeName: pk
          KeyType: HASH
        -
          AttributeName: sk
          KeyType: RANGE
      TableName: shortener-ddb-table
      BillingMode: PAY_PER_REQUEST

Outputs:
  ShortenerAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ShortenerFunction:
    Description: "Shortener Function ARN"
    Value: !GetAtt ShortenerFunction.Arn
  ShortenerFunctionIamRole:
    Description: "Implicit IAM Role created for Shortener function"
    Value: !GetAtt ShortenerFunctionRole.Arn
